adminPanel/src/main/java/com/jjawor/elm/Course_TestTreeBean.java
package com.jjawor.elm;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.Collections;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.event.ActionEvent;
import javax.xml.crypto.Data;

import org.primefaces.model.TreeNode;  
import org.primefaces.model.DefaultTreeNode;  
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.jjawor.elm.schemas.Category;
import com.jjawor.elm.schemas.Course;
import com.jjawor.elm.schemas.Punctation;
import com.jjawor.elm.schemas.Test;
import com.jjawor.elm.schemas.User;
  

@Component("course_testTreeBean")
@Scope(value="session")
public class Course_TestTreeBean implements Serializable{  
	private static final long serialVersionUID = 1L;
	@Autowired
	private transient CourseService courseService;   
	@Autowired
	private transient MessagesController messagesController;//for messagess
	@Autowired
	private SessionData sessionData;
	@Autowired
	private Category_QuestionTreeBean category_QuestionTreeBean;
   
	
	
	//tree data
	private TreeNode root; 
    private final String rootType="kroot";
	private final String courseType="course";
    private final String testType="test";
    //category mini tree data
    private TreeNode categoriesRoot;
    private TreeNode [] categoriesSelectedNodes;

    //selection and creating
	private String newCourse;
	private Test newTest;
    private TreeNode selectedNode;
    private Test selectedTest;
    private Course selectedCourse;
    private boolean result;
    
    
    public boolean isLastSuccess(){
    	return result;
    }

   public void translateSelected(){
	   Object selectedTest=this.getSelectedNode().getData();
	   Object selectedCourse=this.getSelectedNode().getParent().getData();
	   if(selectedTest instanceof TestTreeWrapper && selectedCourse instanceof CourseTreeWrapper){
		   this.setSelectedTest(((TestTreeWrapper) selectedTest).getTest());
		   this.setSelectedCourse(((CourseTreeWrapper) selectedCourse).getCourse());
	   }
   }
    
	@PostConstruct
    public void init() {  
        root = new DefaultTreeNode("Root", null); 
        TreeNode main = new DefaultTreeNode(rootType,"Kursy", root);
        main.setExpanded(true);
        for(Course course:courseService.getCourseTests(sessionData))
        {
        	TreeNode courseNode = new DefaultTreeNode(courseType,new CourseTreeWrapper(course), main); 
        	for(Test test:course.getTests()){
        		new DefaultTreeNode(testType,new TestTreeWrapper(test), courseNode);
        	}
        		
        }
        categoriesRoot=category_QuestionTreeBean.getCategoriesRoot();
    }  
	public void persistCourse(ActionEvent actionEvent){
		Course course=new Course();
		course.setName(getNewCourse());
		result=courseService.persistCourse(sessionData, course)<0?false:true;
		if(result)messagesController.addOperationSuccess(actionEvent);
		else messagesController.addOperationError(actionEvent);
	}
	public void persistTest(ActionEvent actionEvent){
		List<BigInteger> categories=getNewTest().getCategoriesIDs();categories.clear();
		for(TreeNode node:categoriesSelectedNodes){
			Object nodeData=node.getData();
			if(nodeData instanceof CategoryTreeWrapper){
				categories.add(((CategoryTreeWrapper) nodeData).getCategory().getId());
			}
		}
		Object course=selectedNode.getData();
		if(course instanceof CourseTreeWrapper){
		long newId;
		result=(newId=courseService.persistTest(sessionData, getNewTest()))<0?false:true;
		getNewTest().setId(BigInteger.valueOf(newId));
		if(result)result=courseService.assignTestToCourse(sessionData, getNewTest(),((CourseTreeWrapper)course).getCourse())<0?false:true;
		else courseService.deleteTest(sessionData, getNewTest());//rollback if false
		newTest=null;
		}
		else if(getNewTest().getId()!=null){
			result=courseService.persistTest(sessionData, getNewTest())<0?false:true;
		}
		else{result=false;return;}
		
		if(result)messagesController.addOperationSuccess(actionEvent);
		else messagesController.addOperationError(actionEvent);
	}
	/*public void delete(ActionEvent actionEvent){
		Object nodeData=getSelectedNode().getData();
		if(nodeData instanceof CourseTreeWrapper){
		Course course=((CourseTreeWrapper) nodeData).getCourse();
		result=courseService.deleteCourse(sessionData, course);
		}
		else if(nodeData instanceof UserTreeWrapper){
			User user=((UserTreeWrapper) nodeData).getUser();
			Object parentData=getSelectedNode().getParent().getData();
			if(parentData instanceof CourseTreeWrapper){
			result=courseService.unAssign(sessionData, ((CourseTreeWrapper) parentData).getCourse(),user);
			}
			else result=false;
			}
		else result=false;
		if(result)messagesController.addOperationSuccess(actionEvent);
		else messagesController.addOperationError(actionEvent);
	}*/
	public void deleteCourse(ActionEvent actionEvent){
		Object nodeData=getSelectedNode().getData();
		if(nodeData instanceof CourseTreeWrapper){
		Course course=((CourseTreeWrapper) nodeData).getCourse();
		result=courseService.deleteCourse(sessionData, course);
		}
		else result=false;
		if(result)messagesController.addOperationSuccess(actionEvent);
		else messagesController.addOperationError(actionEvent);
	}
	public void deleteTest(ActionEvent actionEvent){
		Object nodeData=getSelectedNode().getData();
		if(nodeData instanceof TestTreeWrapper){
			Test test=((TestTreeWrapper) nodeData).getTest();
			result=courseService.deleteTest(sessionData, test);
		}
		else result=false;
		if(result)messagesController.addOperationSuccess(actionEvent);
		else messagesController.addOperationError(actionEvent);
	}
	public void resetNewTest(ActionEvent actionEvent)
	{
		this.newTest=null;
	}
	public void setSelectedTestAsNew(ActionEvent actionEvent)
	{
		Object data=this.getSelectedNode().getData();
		if(data instanceof TestTreeWrapper){
			this.newTest=((TestTreeWrapper) data).getTest();
			List<BigInteger> toBeSelected=newTest.getCategoriesIDs();
			for(TreeNode node:categoriesRoot.getChildren())
				{
				Object catO=node.getData();
				if(catO instanceof CategoryTreeWrapper){
					Category cat=((CategoryTreeWrapper) catO).getCategory();
					if(toBeSelected.contains(cat.getId()))
						node.setSelected(true);
				}
				}
		}	
	}
	public Course_TestTreeBean getRefreshed(){
		init();
		return this;
	}
	
    public TreeNode getRoot() {  
        return root;  
    }
    
	public TreeNode getSelectedNode() {
		return selectedNode;
	}
	public void setSelectedNode(TreeNode selectedNode) {
		this.selectedNode = selectedNode;
	}
	public String getNewCourse() {
		return newCourse;
	}
	public void setNewCourse(String newCourse) {
		this.newCourse = newCourse;
	}

	public String getRootType() {
		return rootType;
	}

	public String getCourseType() {
		return courseType;
	}

	public String getTestType() {
		return testType;
	}



	public Test getNewTest() {
		if(newTest==null){newTest=new Test();newTest.setPunctation(new Punctation());}
		return newTest;
	}


	public void setNewTest(Test newTest) {
		this.newTest = newTest;
	}



	public TreeNode getCategoriesRoot() {
		return categoriesRoot;
	}



	public void setCategoriesRoot(TreeNode categoriesRoot) {
		this.categoriesRoot = categoriesRoot;
	}
	
	public String getCategoryType() {
		return category_QuestionTreeBean.getCategoryType();
	}



	public TreeNode [] getCategoriesSelectedNodes() {
		return categoriesSelectedNodes;
	}



	public void setCategoriesSelectedNodes(TreeNode [] categoriesSelectedNodes) {
		this.categoriesSelectedNodes = categoriesSelectedNodes;
	}



	public Test getSelectedTest() {
		return selectedTest;
	}



	public void setSelectedTest(Test selectedTest) {
		this.selectedTest = selectedTest;
	}



	public Course getSelectedCourse() {
		return selectedCourse;
	}



	public void setSelectedCourse(Course selectedCourse) {
		this.selectedCourse = selectedCourse;
	}
}

adminPanel/src/main/webapp/WEB-INF/flows/professor/categoryQuestion.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	    		xmlns:ui="http://java.sun.com/jsf/facelets"
	  			xmlns:h="http://java.sun.com/jsf/html"
	  			xmlns:f="http://java.sun.com/jsf/core"
	  			xmlns:p="http://primefaces.org/ui"
	  			xmlns:c="http://java.sun.com/jsp/jstl/core"
				template="standard.xhtml">
<ui:define name="notes">
	<p>
		Clicking "Book" will launch the booking sub-flow (see the subflow state in <strong>main-flow.xml</strong>).
	</p>
	<p>
		The booking flow is protected with Spring Security (see the secured attribute in <strong>booking-flow.xml</strong>).
	</p>
	<p>
		Clicking "Back to Search" will take you to the stateful search results. 
	</p>
</ui:define>
<ui:define name="content">
<h:form id="newCourseForm">
	<p:dialog header="Nowa Kategoria" widgetVar="newCategoryDialog" resizable="false"
              showEffect="explode" hideEffect="explode" dynamic="true">  
  		<p:messages id="messages" autoUpdate="true"  />
        <h:panelGrid id="display" columns="3" cellpadding="4">  
           
            <h:outputLabel for="name" value="Nazwa Kategorii: " />  
            <p:inputText id="name"   
                value="#{category_questionTreeBean.newCategory}" required="true" label="Nazwa Kategorii"/>
            <p:message for="name" />  
        

            <p:commandButton id="saveCourse" value="Zapisz" action="refreshOnSuccess" actionListener="#{category_questionTreeBean.persistCategory}"/>
            <p:commandButton id="cancel" value="Anuluj" immediate="true" action="cancel"/>
        </h:panelGrid>  
    </p:dialog>  
    </h:form>
    
    <h:form id="newQuestionForm">
	<p:dialog header="Nowe Pytanie" widgetVar="newQuestionDialog" resizable="false"
              showEffect="explode" hideEffect="explode" dynamic="true">  
  		<p:messages id="messages" autoUpdate="true"  />
        <h:panelGrid id="display" columns="3" cellpadding="4">  
           
            <h:outputLabel for="text" value="Tekst: " />  
            <p:inputTextarea id="text" rows="5" cols="40" value="#{category_questionTreeBean.newQuestion.text}" required="true" label="Tekst"/>  
            <p:message for="text" /> 
            </h:panelGrid> 
            <p:panel id="answersForm" header="Odpowiedzi" >
            <ui:repeat id="repeat" value="#{category_questionTreeBean.newQuestion.answers}" var="answer">
				
				<p:panel id="category_question"  style="margin-bottom:10px;">
				<h:panelGrid columns="3" cellpadding="4"> 
				<h:outputLabel for="text" value="Tekst: " />  
            <p:inputText id="text" value="#{answer.text}" required="true" label="Tekst"/>  
            <p:message for="text" /> 
            
            <h:outputLabel for="explenationText" value="Wytłumaczenie odpowiedzi: " />  
            <p:inputText id="explenationText" value="#{answer.explenationText}" required="false" label="Wytłumaczenie"/> 
			<p:message for="explenationText" />
            
            
            <h:outputText for="isTrue" value="Czy Prawdziwa " /> 
            <p:selectBooleanButton id="isTrue" value="#{answer.isTrue}" onLabel="Tak" offLabel="Nie" onIcon="ui-icon-check" offIcon="ui-icon-close" />  
            <p:message for="explenationText" />
            <p:commandButton id="deleteAnswer" value="- Usuń odpowiedź" immediate="true" update=":newQuestionForm:answersForm"  action="#{category_questionTreeBean.removeNewAnswerFromNewQuestion(answer)}"/>
				</h:panelGrid>
				</p:panel>
			</ui:repeat>
			<p:commandButton id="addAnswer" value="+ Dodaj odpowiedź" update=":newQuestionForm:answersForm"  actionListener="#{category_questionTreeBean.addNewAnswerToNewQuestion}"/>
			</p:panel>
            
            <h:panelGrid columns="3" cellpadding="4">
            	<p:commandButton id="saveQuestion" value="Zapisz" action="refreshOnSuccess" actionListener="#{category_questionTreeBean.persistQuestion}"/>
        		<p:commandButton id="cancel" value="Anuluj" immediate="true" action="cancel" actionListener="#{category_questionTreeBean.resetNewQuestion}" />
            </h:panelGrid>
           
    </p:dialog>  
    </h:form>
    
    <h:form id="newAnswerForm">
	<p:dialog header="Odpowiedź" widgetVar="newAnswerDialog" resizable="false"
              showEffect="explode" hideEffect="explode" dynamic="true">  
  		<p:messages id="messages" autoUpdate="true"  />
        <h:panelGrid id="display" columns="3" cellpadding="4">  
           
            <h:outputLabel for="text" value="Tekst: " />  
            <p:inputTextarea id="text" rows="5" cols="40" value="#{category_questionTreeBean.newAnswer.text}" required="true" label="Tekst"/>  
            <p:message for="text" /> 
            
            <h:outputLabel for="explenationText" value="Wytłumaczenie odpowiedzi: " />  
            <p:inputTextarea id="explenationText" rows="10" cols="50" value="#{category_questionTreeBean.newAnswer.explenationText}" required="false" label="Wytłumaczenie"/> 
			<p:message for="explenationText" />
            
            <h:outputText for="isTrue" value="Czy Prawdziwa " /> 
            <p:selectBooleanButton id="isTrue" value="#{category_questionTreeBean.newAnswer.isTrue}" onLabel="Tak" offLabel="Nie" onIcon="ui-icon-check" offIcon="ui-icon-close" />  
            <p:message for="explenationText" />
            
            <p:commandButton id="saveAnswer" value="Zapisz" action="refreshOnSuccess" actionListener="#{category_questionTreeBean.persistAnswer}"/>
            <p:commandButton id="cancel" value="Anuluj" immediate="true" action="cancel" actionListener="#{category_questionTreeBean.resetNewAnswer}"/>
        </h:panelGrid>  
    </p:dialog>  
    </h:form>
    
	<h:form id="form">
	<p:panel id="category_question" header="Kategoria - Pytanie" style="margin-bottom:10px;">        
    <p:contextMenu id="treeMenu" for="tree" nodeType="#{category_questionTreeBean.rootType}">  
        <p:menuitem value="Nowa Kategoria" oncomplete="PF('newCategoryDialog').show()" icon="ui-icon-pencil" />  
    </p:contextMenu>
    
    <p:contextMenu id="treeMenu2" for="tree" nodeType="#{category_questionTreeBean.categoryType}">  
        <p:menuitem value="Nowa Kategoria" oncomplete="PF('newCategoryDialog').show()" icon="ui-icon-pencil" />  
        <p:menuitem value="Nowe Pytanie" oncomplete="PF('newQuestionDialog').show()" icon="ui-icon-pencil" />
        <p:menuitem value="Usuń" icon="ui-icon-close" action="refreshOnSuccess" actionListener="#{category_questionTreeBean.deleteCategory}"/>  
    </p:contextMenu>
    
    <p:contextMenu id="treeMenu3" for="tree" nodeType="#{category_questionTreeBean.questionType}">  
        <p:menuitem value="Nowa Odpowiedź" oncomplete="PF('newAnswerDialog').show()" icon="ui-icon-pencil" />  
        <p:menuitem value="Edytuj Pytanie" oncomplete="PF('newQuestionDialog').show()" actionListener="#{category_questionTreeBean.setSelectedQuestionAsNew}" icon="ui-icon-document" />  
        <p:menuitem value="Usuń" icon="ui-icon-close" action="refreshOnSuccess" actionListener="#{category_questionTreeBean.deleteQuestion}"/>  
    </p:contextMenu>
    
    <p:contextMenu id="treeMenu4" for="tree" nodeType="#{category_questionTreeBean.answerTrueType}">  
        <p:menuitem value="Edytuj Odpowiedź" oncomplete="PF('newAnswerDialog').show()" actionListener="#{category_questionTreeBean.setSelectedAnswerAsNew}" icon="ui-icon-document" />  
        <p:menuitem value="Usuń" icon="ui-icon-close" action="refreshOnSuccess" actionListener="#{category_questionTreeBean.deleteAnswer}"/>  
    </p:contextMenu>
    <p:contextMenu id="treeMenu4b" for="tree" nodeType="#{category_questionTreeBean.answerFalseType}">  
        <p:menuitem value="Edytuj Odpowiedź" oncomplete="PF('newAnswerDialog').show()" actionListener="#{category_questionTreeBean.setSelectedAnswerAsNew}" icon="ui-icon-document" />  
        <p:menuitem value="Usuń" icon="ui-icon-close" action="refreshOnSuccess" actionListener="#{category_questionTreeBean.deleteAnswer}"/>  
    </p:contextMenu>
              
            <p:tree value="#{category_questionTreeBean.root}" var="node" id="tree" selectionMode="single"  
            selection="#{category_questionTreeBean.selectedNode}" >  
        		<p:treeNode  type="#{category_questionTreeBean.rootType}">  
            		<h:outputText value="#{node}"/>  
        		</p:treeNode>  
        		<p:treeNode  type="#{category_questionTreeBean.categoryType}">  
            		<h:outputText value="#{node}"/>  
        		</p:treeNode> 
        		<p:treeNode  type="#{category_questionTreeBean.questionType}"  icon="ui-icon-help">  
            		<h:outputText value="#{node}"/>  
        		</p:treeNode> 
        		<p:treeNode  type="#{category_questionTreeBean.answerTrueType}" icon="ui-icon-check">  
            		<h:outputText value="#{node}"/>  
        		</p:treeNode> 
        		<p:treeNode  type="#{category_questionTreeBean.answerFalseType}" icon="ui-icon-close">  
            		<h:outputText value="#{node}"/>  
        		</p:treeNode>
    		</p:tree>
    		
    </p:panel>
    			
	</h:form>
</ui:define>
</ui:composition>

adminPanel/src/main/webapp/WEB-INF/flows/professor/courseUser.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	    		xmlns:ui="http://java.sun.com/jsf/facelets"
	  			xmlns:h="http://java.sun.com/jsf/html"
	  			xmlns:f="http://java.sun.com/jsf/core"
	  			xmlns:p="http://primefaces.org/ui"
	  			xmlns:c="http://java.sun.com/jsp/jstl/core"
				template="standard.xhtml">
<ui:define name="notes">
	<p>
		Clicking "Book" will launch the booking sub-flow (see the subflow state in <strong>main-flow.xml</strong>).
	</p>
	<p>
		The booking flow is protected with Spring Security (see the secured attribute in <strong>booking-flow.xml</strong>).
	</p>
	<p>
		Clicking "Back to Search" will take you to the stateful search results. 
	</p>
</ui:define>
<ui:define name="content">


<h:form id="newCourseForm">
	<p:dialog header="Nowy Kurs" widgetVar="newCourseDialog" resizable="false"
              showEffect="explode" hideEffect="explode" dynamic="true">  
  		<p:messages id="messages" autoUpdate="true"  />
        <h:panelGrid columns="3" cellpadding="4">   
        <h:outputText value="Nazwa Kursu" />  
        <p:inputText id="courseName"   
                value="#{course_userTreeBean.newCourse}" required="true" label="Nazwa Kursu">   
            </p:inputText>  
        <p:message for="courseName" />
            <p:commandButton id="saveCourse" value="Zapisz" action="refreshOnSuccess" actionListener="#{course_userTreeBean.persist}"/>
            <p:commandButton id="cancel" immediate="true" value="Anuluj" action="cancel"/>
        </h:panelGrid>  
    </p:dialog>  
    </h:form>
    <h:form id="newUserForm">
	<p:dialog header="Przypisz Użytkownika" widgetVar="assignUser" resizable="false"
              showEffect="explode" hideEffect="explode" dynamic="true">  
  		<p:messages id="messages" autoUpdate="true"  />
        <h:panelGrid columns="3" cellpadding="4">
        <h:outputText value="Nazwa Użytkownika" />  
        <p:inputText id="userName"   
                value="#{course_userTreeBean.newStudent.login}" required="true" label="Nazwa Użytkownika">   
        </p:inputText> 
        <p:message for="userName" />
            <p:commandButton id="saveUser" value="Przypisz" action="refreshOnSuccess" actionListener="#{course_userTreeBean.assign}"/>
            <p:commandButton id="cancel" immediate="true" value="Anuluj" action="cancel"/>
        </h:panelGrid>  
    </p:dialog>  
    </h:form>




	<h:form id="form">
	<p:panel id="course_user" header="Kurs - Student" style="margin-bottom:10px;">   
	
	
	
	<p:contextMenu id="treeMenu" for="tree" nodeType="#{course_userTreeBean.rootType}">  
        <p:menuitem value="Nowy Kurs" oncomplete="PF('newCourseDialog').show()" icon="ui-icon-pencil" />  
    </p:contextMenu>
    
    <p:contextMenu id="treeMenu2" for="tree" nodeType="#{course_userTreeBean.courseType}">  
        <p:menuitem value="Nowy Kurs" oncomplete="PF('newCourseDialog').show()" icon="ui-icon-pencil" />  
        <p:menuitem value="Nowy Użytkownik" oncomplete="PF('assignUser').show()" icon="ui-icon-pencil" />
        <p:menuitem value="Usuń" icon="ui-icon-close" action="refreshOnSuccess" actionListener="#{course_userTreeBean.delete}"/>  
    </p:contextMenu>
    
    <p:contextMenu id="treeMenu3" for="tree" nodeType="#{course_userTreeBean.userType}">  
         <p:menuitem value="Usuń" icon="ui-icon-close" action="refreshOnSuccess" actionListener="#{course_userTreeBean.delete}"/>  
    </p:contextMenu>
	
    		
    		<p:tree value="#{course_userTreeBean.root}" var="node" id="tree" selectionMode="single"  
            selection="#{course_userTreeBean.selectedNode}" >  
        		<p:treeNode  type="#{course_userTreeBean.rootType}">  
            		<h:outputText value="#{node}"/>  
        		</p:treeNode>  
        		<p:treeNode  type="#{course_userTreeBean.courseType}">  
            		<h:outputText value="#{node}"/>  
        		</p:treeNode> 
        		<p:treeNode  type="#{course_userTreeBean.userType}">  
            		<h:outputText value="#{node}"/>  
        		</p:treeNode> 
    		</p:tree>
    	
    		
    		 </p:panel>
	</h:form>
</ui:define>
</ui:composition>

adminPanel/src/main/webapp/WEB-INF/flows/professor/standard.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	    		xmlns:ui="http://java.sun.com/jsf/facelets"
	  			xmlns:h="http://java.sun.com/jsf/html"
	  			xmlns:f="http://java.sun.com/jsf/core"
	  			xmlns:p="http://primefaces.org/ui"
	  			xmlns:c="http://java.sun.com/jsp/jstl/core"
				template="/WEB-INF/layouts/standard.xhtml">

<ui:define name="side_menu">
<h:form>
	<p:tieredMenu  style="width:250px">
            <p:menuitem value="Kurs - Student" action="toCourseUser" icon="ui-icon-arrowthick-1-ne"/>
            <p:separator />
            <p:menuitem value="Kategoria - Pytanie" action="toCategoryQuestion" icon="ui-icon-arrowthick-1-ne"/>
            <p:separator />
            <p:menuitem value="Kurs - Test - Wyniki Studentów" action="toCourseTest" icon="ui-icon-arrowthick-1-ne"/>
    </p:tieredMenu  >
</h:form>

</ui:define>

<ui:define name="menu">
<h:form>
	<p:menubar>
            <p:menuitem value="Kurs - Student" action="toCourseUser" icon="ui-icon-arrowthick-1-ne"/>
            <p:menuitem value="Kategoria - Pytanie" action="toCategoryQuestion" icon="ui-icon-arrowthick-1-ne"/>
            <p:menuitem value="Kurs - Test - Wyniki Studentów" action="toCourseTest" icon="ui-icon-arrowthick-1-ne"/>
    </p:menubar  >
</h:form>

</ui:define>
</ui:composition>

adminPanel/src/main/webapp/WEB-INF/flows/professor/studentResults.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	    		xmlns:ui="http://java.sun.com/jsf/facelets"
	  			xmlns:h="http://java.sun.com/jsf/html"
	  			xmlns:f="http://java.sun.com/jsf/core"
	  			xmlns:p="http://primefaces.org/ui"
	  			xmlns:c="http://java.sun.com/jsp/jstl/core"
				template="/WEB-INF/layouts/standard.xhtml">
<ui:define name="notes">
	<p>
		Clicking "Book" will launch the booking sub-flow (see the subflow state in <strong>main-flow.xml</strong>).
	</p>
	<p>
		The booking flow is protected with Spring Security (see the secured attribute in <strong>booking-flow.xml</strong>).
	</p>
	<p>
		Clicking "Back to Search" will take you to the stateful search results. 
	</p>
</ui:define>
<ui:define name="content">






	<h:form id="form">
	<p:panel id="student_results" header="Wyniki Studentów" style="margin-bottom:10px;">   
	
	
	<p:dataTable id="users" var="result" value="#{resultsModel}" paginator="true" rows="10" 
	paginatorTemplate="{RowsPerPageDropdown} {FirstPageLink} {PreviousPageLink} 
	{CurrentPageReport} {NextPageLink} {LastPageLink}" 
	rowsPerPageTemplate="5,10,15" lazy="true">
       <p:column>
			<f:facet name="header">Imię Studenta</f:facet>
			#{result.user.name}
		</p:column>
		<p:column>
			<f:facet name="header">Numer indeksu</f:facet>
			#{result.user.indexNumber}
		</p:column>
		<p:column>
			<f:facet name="header">Liczba poprawnych odpowiedzi</f:facet>
			#{result.points}
		</p:column>
		<p:column>
			<f:facet name="header">Ocena</f:facet>
			#{result.mark}
		</p:column>
		<p:column>
			<f:facet name="header">Data Zakończenia</f:facet>
			#{resultsModel.getDateFormat().format(result.getEndDate())}
		</p:column>
	</p:dataTable>
    		
    		 </p:panel>
	</h:form>
</ui:define>
</ui:composition>